<?xml version="1.0"?>
<package format="3">
  <name>wheel_velocities_publisher</name>
  <version>0.0.0</version>
  <description>Incremental learner-owned wheel speed publisher for Checkpoint16.</description>
  <maintainer email="194167803+Cooper-Yu@users.noreply.github.com">Cooper-Yu</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>